### ISSUE TITLE
怎么给联系人绑点击事件

### ISSUE THREAD

**Issue by tinybright** [jiang111/IndexRecyclerView#1]

**Comment by jiang111** [comment]
和普通的recyclerview绑定事件写法一样的，例如在onBindViewHolder的方法里这么写:
swipeRoot.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(v.getContext(), "你点击了" + position, Toast.LENGTH_SHORT).show();
            }
        });

**Comment by tinybright** [comment]
我忘记Toast.show()了
