### ISSUE TITLE
工具类转换错误

### ISSUE THREAD

**Issue by Sum-sdl** [jiang111/IndexRecyclerView#12]
/**
     * 单字解析 * * @param str * @return
     */
    public String convert(String str) {
        String result = null;
        if (str == null || str.length() == 0) {
            return null;
        }
        int ascii = getChsAscii(str);
        if (ascii > 0 && ascii < 160) {
            result = String.valueOf((char) ascii);
        } else {
            **if (ascii == 0) {//输入全拼音
                return str;
            }**
            for (int i = (pyvalue.length - 1); i >= 0; i--) {
                if (pyvalue[i] <= ascii) {
                    result = pystr[i];
                    break;
                }
            }
        }
        return result;
    }

**Comment by jiang111** [comment]
fixed
