### ISSUE TITLE
点击SlideBar 跳转问题

### ISSUE THREAD

**Issue by gzfgeh** [jiang111/IndexRecyclerView#4]
当屏幕中出现H J K 等的时候，并且H在顶部，当我点击SlideBar上面的K的时候，RecyclerView没有跳转，只有当屏幕中没有K出现的时候，RecyclerView才会跳转到K，测试下来就是RecyclerView的scrollToPosition问题，但是不知道如何解决？

**Comment by jiang111** [comment]
这个问题确实存在,我也一直没有找到好的方法,你可以试一下 LinearLayoutManager.scrollToPositionWithOffset(int, int) 这个方法

**Comment by jiang111** [comment]
无聊看了一下官方文档，然后就有了答案 mRecyclerView.getLayoutManager().scrollToPosition(position);
唉，文档真的很重要

**Comment by gzfgeh** [comment]
恩，不过我用这个方法解决了
layoutManager.scrollToPositionWithOffset(position, 0);
